In [8]:
import pandas as pd
df=pd.read_csv('laptops.csv')
df.columns = df.columns.str.strip()
df

,Brand,Resolution,Size,Selling Price,Original Price,Operating System,Rating
0,TOSHIBA,Ultra HD LED,55,37999,54990,VIDAA,4.3
1,TCL,QLED Ultra HD,55,52999,129990,Android,4.4
2,realme,HD LED,32,13999,17999,Android,4.3
3,Mi,HD LED,32,14999,19999,Android,4.4
4,realme,HD LED,32,12999,21999,Android,4.3
...,...,...,...,...,...,...,...
907,SONY,Full HD LED,43,44999,57900,Linux,4.4
908,SONY,Full HD LED,40,41499,51900,Linux,4.6
909,SONY,Ultra HD LED,65,149990,184990,Linux,4.3
910,SONY,HD LED,32,32900,32900,Linux,4.4
911,SONY,Full HD LED,43,56900,56900,Linux,4.6

# 1️⃣ Filtering based on condition
 Q1: Display all rows where the Brand is "SAMSUNG" AND the Selling Price is less than 50000.

In [10]:
df[(df["Brand"] == "SAMSUNG") &
   (df["Selling Price"] < 50000)]

,Brand,Resolution,Size,Selling Price,Original Price,Operating System,Rating
28,SAMSUNG,Ultra HD LED,43,38990,54900,Tizen,4.3
56,SAMSUNG,HD LED,32,18490,20900,Tizen,4.3
77,SAMSUNG,HD LED,32,16290,16400,Tizen,4.3
97,SAMSUNG,Full HD LED,32,20880,24275,Tizen,4.2
117,SAMSUNG,Full HD LED,43,32999,53900,Tizen,4.4
118,SAMSUNG,Full HD LED,43,36580,39900,Tizen,4.3
152,SAMSUNG,Ultra HD LED,43,41900,49990,Tizen,NaN
156,SAMSUNG,HD LED,32,21600,22900,Tizen,4.5
167,SAMSUNG,Ultra HD LED,43,45400,56900,Linux,4.3
170,SAMSUNG,HD LED,32,29900,29900,Tizen,3.8
196,SAMSUNG,Ultra HD LED,43,44870,54900,Tizen,NaN
197,SAMSUNG,Ultra HD LED,43,38999,48900,Tizen,4.3
241,SAMSUNG,Ultra HD LED,43,49990,62900,Tizen,NaN
257,SAMSUNG,Full HD LED,43,38990,56945,Tizen,NaN
318,SAMSUNG,HD LED,32,18490,22500,Tizen,4.0
334,SAMSUNG,Full HD LED,43,45785,45900,Tizen,NaN
338,SAMSUNG,Full HD LED,48,49990,77900,Tizen,3.7
341,SAMSUNG,Ultra HD LED,43,44990,78000,Tizen,NaN
371,SAMSUNG,HD LED,24,15200,15200,Tizen,4.2
376,SAMSUNG,Full HD LED,49,45700,66900,Tizen,4.2
382,SAMSUNG,HD LED,32,19599,25900,Tizen,4.3
394,SAMSUNG,Full HD LED,43,36990,38900,Tizen,4.1
403,SAMSUNG,HD LED,32,23000,25900,Tizen,4.4
433,SAMSUNG,Full HD LED,43,48900,48900,Tizen,4.2
459,SAMSUNG,HD LED,32,17999,23890,Tizen,4.2
475,SAMSUNG,HD LED,32,26900,26900,Tizen,4.0
509,SAMSUNG,Full HD LED,43,31990,38900,Tizen,4.4
510,SAMSUNG,Full HD LED,43,36890,45900,Tizen,4.7
511,SAMSUNG,Full HD LED,43,39999,49900,Tizen,4.3
519,SAMSUNG,Full HD LED,43,34999,58900,Tizen,4.5
526,SAMSUNG,Ultra HD LED,43,43751,77900,Tizen,4.4
530,SAMSUNG,Ultra HD LED,43,36999,66900,Tizen,4.5
537,SAMSUNG,Full HD LED,43,36514,46900,Tizen,4.5
542,SAMSUNG,HD LED,32,11999,21900,Tizen,4.4
551,SAMSUNG,Full HD LED,43,36999,58900,Tizen,4.3
554,SAMSUNG,Ultra HD LED,43,36106,69900,Tizen,4.3
555,SAMSUNG,Full HD LED,43,24726,45900,Tizen,3.8
561,SAMSUNG,HD LED,32,15210,27900,Tizen,4.3
573,SAMSUNG,Ultra HD LED,43,35999,52900,Tizen,4.5
578,SAMSUNG,HD LED,32,17499,20900,Tizen,4.3
580,SAMSUNG,Full HD LED,40,19929,43476,Tizen,4.3
622,SAMSUNG,Full HD LED,40,33000,43850,Tizen,3.8
625,SAMSUNG,Full HD LED,32,20126,40900,Tizen,4.4
626,SAMSUNG,Full HD LED,32,15990,34900,Tizen,4.2
660,SAMSUNG,HD LED,32,13990,28900,Tizen,4.5
709,SAMSUNG,HD LED,32,35700,35700,Tizen,3.3

# 2️⃣ Conditional filtering with multiple conditions
 Q2: Display only the Brand, Size, and Rating columns for laptops where the Operating System is "Android " AND Rating is greater than or equal to 4.0.

In [31]:
df[(df["Resolution"].str.strip() == "HD LED") &
         (df["Operating System"].str.strip() == "Android") &
         (df["Rating"] >= 4.0)][["Brand", "Size ", "Rating"]]

                Brand  Size   Rating
2             realme      32     4.3
3                 Mi      32     4.4
4             realme      32     4.3
5             OnePlus     32     4.3
13                Mi      32     4.3
..                ...    ...     ...
810             LumX      24     4.3
816  MarQ by Flipkart     32     4.1
826          Micromax     20     4.1
835             Onida     24     4.2
836             Onida     32     4.7

[84 rows x 3 columns]

# 3️⃣ Drop rows with missing values
 Q3: Drop all rows where the Rating column has NaN values

In [32]:
df.dropna(subset=["Rating"])

,Brand,Resolution,Size,Current Price,MRP,Operating System,Rating
0,TOSHIBA,Ultra HD LED,55,37999,54990,VIDAA,4.3
1,TCL,QLED Ultra HD,55,52999,129990,Android,4.4
2,realme,HD LED,32,13999,17999,Android,4.3
3,Mi,HD LED,32,14999,19999,Android,4.4
4,realme,HD LED,32,12999,21999,Android,4.3
...,...,...,...,...,...,...,...
907,SONY,Full HD LED,43,44999,57900,Linux,4.4
908,SONY,Full HD LED,40,41499,51900,Linux,4.6
909,SONY,Ultra HD LED,65,149990,184990,Linux,4.3
910,SONY,HD LED,32,32900,32900,Linux,4.4
911,SONY,Full HD LED,43,56900,56900,Linux,4.6

# 4️⃣ Fill missing values
 Q4: Replace all NaN values in the Operating System column with the string "Unknown".

In [18]:
df["Operating System"].fillna("Unknown", inplace=True)
df

C:\Users\Shamil\AppData\Local\Temp\ipykernel_14828\4153500463.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Operating System"].fillna("Unknown", inplace=True)

,Brand,Resolution,Size,Selling Price,Original Price,Operating System,Rating
0,TOSHIBA,Ultra HD LED,55,37999,54990,VIDAA,4.3
1,TCL,QLED Ultra HD,55,52999,129990,Android,4.4
2,realme,HD LED,32,13999,17999,Android,4.3
3,Mi,HD LED,32,14999,19999,Android,4.4
4,realme,HD LED,32,12999,21999,Android,4.3
...,...,...,...,...,...,...,...
907,SONY,Full HD LED,43,44999,57900,Linux,4.4
908,SONY,Full HD LED,40,41499,51900,Linux,4.6
909,SONY,Ultra HD LED,65,149990,184990,Linux,4.3
910,SONY,HD LED,32,32900,32900,Linux,4.4
911,SONY,Full HD LED,43,56900,56900,Linux,4.6

# 5️⃣ Rename columns
 Q5: Rename the column "Selling Price" to "Current Price" and "Original Price" to "MRP".

In [34]:
df.rename(columns={
    "Selling Price": "Current Price",
    "Original Price": "MRP"
}, inplace=True)

df

,Brand,Resolution,Size,Current Price,MRP,Operating System,Rating
0,TOSHIBA,Ultra HD LED,55,37999,54990,VIDAA,4.3
1,TCL,QLED Ultra HD,55,52999,129990,Android,4.4
2,realme,HD LED,32,13999,17999,Android,4.3
3,Mi,HD LED,32,14999,19999,Android,4.4
4,realme,HD LED,32,12999,21999,Android,4.3
...,...,...,...,...,...,...,...
907,SONY,Full HD LED,43,44999,57900,Linux,4.4
908,SONY,Full HD LED,40,41499,51900,Linux,4.6
909,SONY,Ultra HD LED,65,149990,184990,Linux,4.3
910,SONY,HD LED,32,32900,32900,Linux,4.4
911,SONY,Full HD LED,43,56900,56900,Linux,4.6

# 6️⃣ Count occurrences using value_counts()
 Q6: Find how many laptops are available for each Brand using value_counts().

In [22]:
df[df["Resolution"].str.strip() == "HD LED"]["Brand"].value_counts()

Brand
SAMSUNG             16
LG                  14
Micromax            14
TCL                  9
T-Series             9
SONY                 8
Croma                8
IMPEX                8
Lloyd                8
Candes               6
Power Guard          6
Mi                   5
Thomson              5
Adsun                5
Panasonic            5
Sansui               5
Haier                5
MarQ by Flipkart     4
KODAK                4
Dyanora              4
Onida                4
Blaupunkt            4
HUIDI                4
LumX                 4
G-TEN                4
Dektron              4
realme               3
Acer                 3
PHILIPS              3
VG                   3
Onix                 3
Intex                3
Vu                   3
KRISONS              3
AISEN                3
Coocaa               2
TOSHIBA              2
MOTOROLA             2
Hisense              2
RGL                  2
BPL                  2
CloudWalker          2
DETEL                2
JVC                  2
Sharp                2
OnePlus              1
Infinix              1
Nokia                1
Sun King             1
Skyworth             1
Maser                1
iFFALCON by TCL      1
Akai                 1
Compaq               1
MURPHY               1
Name: count, dtype: int64

# 7️⃣ Grouping and aggregation
 Q7: Group the DataFrame by Brand and calculate the sum of Selling price for each brand.
Then, sort the result in descending order of average selling price.

In [23]:
df.groupby("Brand").agg(
    Total_Price=("Selling Price", "sum"),
    Average_Price=("Selling Price", "mean")
).sort_values("Average_Price", ascending=False)

                  Total_Price  Average_Price
Brand
Sharp                 1197376  149672.000000
Samsung                729780  121630.000000
SAMSUNG              14897292  106409.228571
LG                   11823557   96914.401639
Hisense                897954   89795.400000
SONY                  5539256   89342.838710
TCL                   2455126   55798.318182
iFFALCON by TCL       1030454   54234.421053
Panasonic             1604819   53493.966667
Akai                   312017   52002.833333
OnePlus                426382   47375.777778
Vu                    1072947   46649.869565
Compaq                 229995   45999.000000
Sanyo                   90998   45499.000000
Weston                 216950   43390.000000
Oxygen                 120979   40326.333333
Nokia                  427489   38862.636364
TOSHIBA                505087   38852.846154
MOTOROLA               575985   38399.000000
Sansui                 678095   37671.944444
Haier                  659092   36616.222222
AISEN                  283700   35462.500000
BPL                    138469   34617.250000
Onix                   273730   34216.250000
Lloyd                  751560   34161.818182
PHILIPS                579935   34113.823529
JVC                    194978   32496.333333
CloudWalker            290982   32331.333333
Acer                   284982   31664.666667
Mi                     584954   30787.052632
Power Guard            335607   30509.727273
Onida                  356486   29707.166667
IMPEX                  374652   28819.384615
Intex                  191385   27340.714286
Micromax               671739   26869.560000
Thomson                454482   25249.000000
Sun King                24999   24999.000000
LumX                   149150   24858.333333
Coocaa                 219982   24442.444444
realme                 170993   24427.571429
Blaupunkt              355685   23712.333333
KODAK                  354976   23665.066667
Croma                  268388   22365.666667
VG                      77969   19492.250000
HUIDI                  108994   18165.666667
DETEL                   54332   18110.666667
MarQ by Flipkart       141992   17749.000000
T-Series               188971   17179.181818
Infinix                 51497   17165.666667
G-TEN                  135347   16918.375000
Dyanora                 93094   15515.666667
Adsun                  106543   15220.428571
Candes                 160988   13415.666667
MURPHY                  51269   12817.250000
RGL                     99958   11106.444444
Skyworth                 8659    8659.000000
Maser                    7499    7499.000000
Dektron                 26896    6724.000000
KRISONS                 17597    5865.666667

# 8️⃣ Sorting values
 Q9: Sort the DataFrame first by Selling Price in ascending order and then by Rating in descending order.

In [55]:
df.sort_values(["Selling Price", "Rating"],ascending=[True, False])

,Brand,Resolution,Size,Selling Price,Original Price,Operating System,Rating
858,RGL,Full HD LED,20,4849,8990,HomeOS,3.9
614,RGL,Full HD LED,21,5200,9420,HomeOS,3.9
859,RGL,Full HD LED,21,5200,9420,HomeOS,3.9
826,Micromax,HD LED,20,5364,10990,Android,4.1
860,RGL,Full HD LED,24,5459,12000,HomeOS,3.9
...,...,...,...,...,...,...,...
720,SAMSUNG,Full HD LED,75,419900,419900,Tizen,NaN
885,Sharp,Full HD LED,70,449900,449900,Linux,NaN
228,SONY,Ultra HD LED,65,469999,529900,Android,5.0
276,SAMSUNG,QLED Ultra HD,65,470900,470900,Tizen,NaN
507,Hisense,QLED Ultra HD,75,499990,499990,Android,NaN


# 9️⃣ Groupby with sort
Q10: Find the top 3 brands with the highest selling price.
Display their brand names .

In [56]:
df.groupby("Brand")["Selling Price"].sum().sort_values(ascending=False).head(3)

Brand
SAMSUNG    14897292
LG         11823557
SONY        5539256
Name: Selling Price, dtype: int64