
# 1️⃣ Create a DataFrame

Create a DataFrame with columns: Name, Age, and Marks
Include 4 student records with at least one missing value.
(Hint: Use a dictionary and pd.DataFrame())

In [1]:
import pandas as pd
data = {
    'Name': ['samil', 'sabu', 'Rahul', 'sahal'],
    'Age': [21, 22, None, 24],
    'Marks': [85, 92, 78, 95]
}

df = pd.DataFrame(data)
print("1. DataFrame:")
print(df)

1. DataFrame:
    Name   Age  Marks
0  samil  21.0     85
1   sabu  22.0     92
2  Rahul   NaN     78
3  sahal  24.0     95

# 2️⃣ Add a new column

Add a new column "Grade" with letter grades (A, B, C, etc.)

In [2]:
df['Grade']=['A','B','A','C']
print('ADD GRADE')
df

ADD GRADE

    Name   Age  Marks Grade
0  samil  21.0     85     A
1   sabu  22.0     92     B
2  Rahul   NaN     78     A
3  sahal  24.0     95     C

# 3️⃣ Access specific columns

Display only the 'Name' and 'Marks' columns.

In [9]:
df[['Name','Marks']]

    Name  Marks
0  samil     85
1   sabu     92
2  Rahul     78
3  sahal     95

# 4️⃣ Count missing values

Count the number of missing values in each column.
(Hint: df.isnull().sum())

In [10]:
df.isnull().sum()

Name     0
Age      1
Marks    0
Grade    0
dtype: int64

# 5️⃣ Handle missing values

Replace all missing values in 'Age' with the mean age.
Hint: df['Age'].fillna(df['Age'].mean(), inplace=True))

In [13]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df['Age'])

0    21.000000
1    22.000000
2    22.333333
3    24.000000
Name: Age, dtype: float64

# 6️⃣ Modify a specific cell

Change the Name in the 3rd row (index 2) to 'Sonu'.
(Hint: df.loc[2, 'Name'] = 'Sonu')

In [15]:
df.loc[2,'Name']='sonu'
df

    Name        Age  Marks Grade
0  samil  21.000000     85     A
1   sabu  22.000000     92     B
2   sonu  22.333333     78     A
3  sahal  24.000000     95     C

# 7️⃣ Add new rows to the DataFrame

Add two new rows:
{'Name': 'Kumar', 'Age': 20, 'Marks': 90}
{'Name': 'Rahul', 'Age': 26, 'Marks': 85}
(Hint: Use pd.concat)

In [17]:
new_rows = pd.DataFrame([
    {'Name': 'Kumar', 'Age': 20, 'Marks': 90, 'Grade': 'A'},
    {'Name': 'Rahul', 'Age': 26, 'Marks': 85, 'Grade': 'B'}
])
df=pd.concat([df,new_rows],ignore_index=True)
df

    Name        Age  Marks Grade
0  samil  21.000000     85     A
1   sabu  22.000000     92     B
2   sonu  22.333333     78     A
3  sahal  24.000000     95     C
4  Kumar  20.000000     90     A
5  Rahul  26.000000     85     B
6  Kumar  20.000000     90     A
7  Rahul  26.000000     85     B

# 8️⃣ Access data using loc

Access and print 'Name' and 'Marks' for the student at index 0.
(Hint: df.loc[0, ['Name', 'Marks']])

In [ ]:
df.loc[0, ['Name', 'Marks']]

Name     Rahul
Marks       85
Name: 5, dtype: object

# 9️⃣ Slicing rows and columns using loc

Display 'Name' and 'Marks' for rows 0 to 3.
(Hint: df.loc[0:3, ['Name', 'Marks']])

In [22]:
df.loc[0:3, ['Name', 'Marks']]

    Name  Marks
0  samil     85
1   sabu     92
2   sonu     78
3  sahal     95

# 🔟 Access rows and columns using iloc

 Display the first and third rows, and first two columns.
(Hint: df.iloc[0:3:2, 0:2])

In [23]:
df.iloc[0:3:2, 0:2]

    Name        Age
0  samil  21.000000
2   sonu  22.333333

# 1️⃣1️⃣ Aggregate functions

Calculate and display:
 Mean Age
 Minimum Age
 Maximum Age
 Count of Age values

In [24]:
print("Mean Age:", df['Age'].mean())
print("Minimum Age:", df['Age'].min())
print("Maximum Age:", df['Age'].max())
print("Count of Age:", df['Age'].count())

Mean Age: 22.666666666666664
Minimum Age: 20.0
Maximum Age: 26.0
Count of Age: 8

# 1️⃣2️⃣ Grouping and aggregation

Group the DataFrame by 'Name' and compute the mean Age for each Name.
(Hint: df.groupby('Name')['Age'].mean())

In [25]:
df.groupby('Name')['Age'].mean()

Name
Kumar    20.000000
Rahul    26.000000
sabu     22.000000
sahal    24.000000
samil    21.000000
sonu     22.333333
Name: Age, dtype: float64

# 🧠 Bonus Challenge

Sort the DataFrame by 'Marks' in descending order and
display the top 3 students.
(Hint: df.sort_values(by='Marks', ascending=False).head(3))

In [26]:
df.sort_values(by='Marks', ascending=False).head(3)

    Name   Age  Marks Grade
3  sahal  24.0     95     C
1   sabu  22.0     92     B
6  Kumar  20.0     90     A